listener:
  slotName: myslot_1
  refreshConnection: 30s
  heartbeatInterval: 10s
logger:
  caller: false
  level: info
  humanReadable: true
database:
  host: localhost
  port: 5432
  name: test_db
  user: back
  debug: false
  password: pass
  filter:
    tables:
      users:
        topic: datasync
        actions:
          - "insert"
          - "update"
          - "delete"
nats:
  address: localhost:4222
  clusterID: test-cluster
  clientID: wal-listener
  topicPrefix: "pre"